export const AUTH_USER = 'AUTH_USER';
export const DEAUTH_USER = 'DEAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const FETCH_SENT_MESSAGES = 'FETCH_SENT_MESSAGES';
export const FETCH_RECEIVED_MESSAGES = 'FETCH_RECEIVED_MESSAGES';
